#!/bin/sh
#
# Runs tests whenever a files change

if ! test ./run-continuous-tests = "$0"
then echo "Invoke as ./run-continuous-tests";
     exit 1
fi

if which nix-shell >/dev/null
then nix-shell \
          -p "haskellngPackages.ghcWithPackages (pkgs: with pkgs; [stm])" \
          -p 'inotify-tools' \
          --run "runhaskell autotest.hs"
else runhaskell autotest.hs
fi
