#!/bin/sh
#
# Runs the tests in nix-shell

if ! test ./run-tests = "$0"
then echo "Invoke as ./run-tests";
     exit 1
fi

if which nix-shell >/dev/null
then nix-shell --show-trace --pure --run 'cabal test'
else cabal test
fi
