#!/bin/sh
#
# A wrapper for ghci with the right dependencies and settings

if ! test ./run-ghci = "$0"
then echo "Invoke as ./run-ghci";
     exit 1
fi

if which nix-shell >/dev/null
then nix-shell --show-trace --pure --run "cabal repl"
else cabal repl
fi
