#!/bin/sh
#
# Runs timekeeperd

if ! test ./run-timekeeperd-compiled = "$0"
then echo "Invoke as ./run-timekeeperd-compiled";
     exit 1
fi

if which nix-shell >/dev/null
then nix-shell \
          -p "haskellngPackages.ghcWithPackages (pkgs: with pkgs; [stm])" \
          -p 'inotify-tools' \
          --run "cabal run timekeeperd"
else cabal run timekeeperd
fi
