#!/bin/sh
#
# This script must be run when the .cabal file changes.
#

if ! test ./run-cabal2nix = "$0"
then echo "Invoke as ./run-cabal2nix";
     exit 1
fi

if nix-shell --pure --run 'cabal2nix .' >timekeeper.nix.$$ \
   && mv timekeeper.nix.$$ timekeeper.nix
then echo "cabal2nix done."
else echo "cabal2nix failure."; exit 1
fi
